CREATE DATABASE  COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
ROLL_NO INT,
NAME varchar(50),
MARKS INT ,
AGE INT NOT NULL
);
INSERT INTO STUDENT (ID,ROLL_NO,NAME,MARKS,AGE)
values
(10,101,"IMU",100,28),
(11,102,"ISHU",98,30);


SHOW TABLES ;
SHOW DATABASES;


CREATE TABLE STU(
ROLL INT PRIMARY KEY,
COURSE varchar(50)
);
INSERT INTO STU (ROLL,COURSE)
values
(101,"ENGLISH"),
(102,"SCIENCE");

SELECT * FROM STU;
DROP TABLE STU ;

CREATE TABLE TEMP(
STUDENT_ROLL_NO INT,
FOREIGN KEY (STUDENT_ROLL_NO) references STU(ROLL)
ON DELETE CASCADE
ON update CASCADE
);
SELECT * FROM TEMP;

DROP database college;

SELECT * FROM STUDENT 
INNER JOIN STU
ON STUDENT.ROLL_NO=STU.ROLL;

SELECT * FROM STUDENT 
LEFT JOIN STU
ON STUDENT.ROLL_NO=STU.ROLL;

SELECT * FROM STUDENT 
RIGHT JOIN STU
ON STUDENT.ROLL_NO=STU.ROLL;


SELECT * FROM STUDENT 
FULL JOIN STU
ON STUDENT.ROLL_NO=STU.ROLL;


CREATE DATABASE CITY ;
USE CITY;
CREATE TABLE INFO (
CITY_ID INT primary key,
NAME varchar(50)
constraint NAME_CHECK CHECK  (NAME ="PUNE")
);
INSERT INTO INFO (CITY_ID,NAME)
values
(101,"PUNE"),
(102,"PUNE");
SELECT * FROM INFO;
DROP TABLE INFO;



CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY,
SALARY INT,
NAME varchar(50),
AGE INT NOT NULL
);
INSERT INTO EMPLOYEE(ID,SALARY,NAME,AGE)
values
(10,10000,"IMU",28),
(11,102000,"ISHU",30),
(12,100000,"ANA ",18),
(13,102000,"SHIV",30),
(14,10000,"AMU",38),
(15,10400,"ILIA",35)
;

SELECT * FROM EMPLOYEE where AGE >30;
SELECT * FROM EMPLOYEE where AGE >30 OR SALARY=102000;

SELECT * FROM EMPLOYEE where AGE  BETWEEN 20 AND 30;
SELECT * FROM EMPLOYEE where NAME IN ("SHIV");
SELECT * FROM EMPLOYEE where NAME NOT IN ("SHIV");

SELECT * FROM EMPLOYEE  LIMIT 3;
SELECT * FROM EMPLOYEE 
ORDER BY SALARY DESC
LIMIT 3
;

SELECT avg(SALARY) FROM EMPLOYEE ;
SELECT max(SALARY) FROM EMPLOYEE ;
SELECT count(SALARY) FROM EMPLOYEE ;
SELECT min(SALARY) FROM EMPLOYEE ;
SELECT sum(SALARY) FROM EMPLOYEE ;

SELECT COUNT(NAME) FROM EMPLOYEE 
GROUP BY AGE ;

SELECT COUNT(NAME) FROM EMPLOYEE 
GROUP BY AGE 
HAVING AGE >30;


SET SQL_SAFE_UPDATES=0;
UPDATE EMPLOYEE
SET AGE=25
WHERE AGE=30;


delete FROM EMPLOYEE
WHERE AGE <20;
SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE
ADD column WEIGHT INT ;
SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE
DROP column WEIGHT  ;
SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE
RENAME TO EMPLOYEE_INFO ;

SELECT * FROM EMPLOYEE_INFO;

ALTER TABLE EMPLOYEE_INFO
CHANGE ID  EMPLOYEE_ID INT  ;
SELECT * FROM EMPLOYEE_INFO;




